// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/Media/BibleVerse.jsx.png"
    | "/Media/Home.jsx.png"
    | "/Media/Preview1.png"
    | "/Media/Preview2.png"
    | "/Media/Preview3.png"
    | "/content-scripts/content.js"
    | "/icon/128.png"
    | "/icon/16.png"
    | "/icon/24.png"
    | "/icon/32.png"
    | "/icon/48.png"
    | "/icon/64.png"
    | "/icon/96.png"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
